name: event_taxi
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/tappeddev/event_taxi
author: Tapped <contact@tapped.dev>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.8
