name: event_taxi
description: A starting point for Dart libraries or applications.
version: 0.1.5
homepage: https://github.com/tappeddev/event_taxi
author: Tapped <contact@tapped.dev>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.6

dev_dependencies:
  test: ^1.5.2
