name: event_taxi
description: EventTaxi could be used to send events through different layers of the application decoupled from the architecture.
version: 1.0.0
homepage: https://github.com/tappeddev/event_taxi

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.8
