name: event_taxi
description: A starting point for Dart libraries or applications.
version: 0.1.1
homepage: https://github.com/tikkrapp/event_taxi
author: Tikkr <info@tikkr.app>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta: ^1.1.6

dev_dependencies:
  test: ^1.5.2
